language: node_js
node_js:
- 6.9.0
before_install:
- git config --global push.default matching
- git config --global user.name "qiwihui via Travis CI"
- git config --global user.email "qwh005007@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
install:
- git submodule update --init
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate --deploy --quiet
branches:
  only:
  - master
cache:
  directories:
  - node_modules
env:
  global:
  - secure: IYXTVHItgbEnJICDsjEpyO9mciOs4KcMFfr8zfF5qf31HsuAmsoXDJWpXzw6NMlFhBhZEHSG0jq9VotJVzamCFQpBKvBAyoFrjlM4ZG03Xbm+vPLOGhH1E63C4ggw9Ceb6Rnmn9aP8LYt7a3Su1wcNeahYlZjzYjr4+A3Gpu4XGfwQybhwLA0IYP4tKN2FejdWqEkcR9kImzZMwnUKXaEV968CrZqHLC/s0FVSlqNKt71M5GGzFsEE8j6BbYugqjlU6eMeSSDqKyBCLr1Qm788opvyiDwsG8K6/ukJpo0MyWeRfSrP7GPtSE+epmDh26ALty6uZKuk/gMdKrGZujOqqBsCvXjWfSFWU+BM7XG8+lF4JcJwEx/vQ5Brz6cDhf5zVLOrKSXfLhinY2EqqPg796sFYTgJSyLlxVPX1qLltRFegdbKGqfHEEk0n9FsZpxfhjZNWyB+act9RCne0E6pJl/i9h5znezUF4zS1pOTxM5/qfILMoBJgZn/PEdFzFtOlmA8y7nnGeOzxkrZtB7tI4t9Hjg8gR1qe8sPXYM60kpVe60QzrdOe6ILnGI2qG6YFmAVBXWjy0Wc8OaGMM0/oJ6h7HswpUq5yMogupAzeCJHbNIul+lxKYV+ADb1v2ThLlFaudyV4pjvCdEfNcgGgK5Zs7e/5tJDuGvXhNmWA=
notifications:
  email:
    recipients:
    - qwh005007@gmail.com
    on_success: change
    on_failure: always
