## Dependencies
#markdown: redcarpet
#highlighter: pygments
#redcarpet:
#    extensions:
#        - footnotes
#
## Permalinks
#permalink: pretty
#
## Allows custom plugins to run
#safe: false
#
## Setup
#title: Qiwihui
#tagline: "chris.qiu's Thoughts and Writings."
#sidebar_description: "programming, lifehacking and mathematics"
#
#meta_description: "All things web, mathematics and programming."
#keywords: [Programming, Python, Golang, Mathematics]
#
#url: http://daozhang.info
#baseurl: /
#encoding: utf-8
#
#exclude:
#    - Gemfile
#    - Gemfile.lock
#    - _config.yml
#
#author:
#    name: 'Chris Qiu'
#    url: http://daozhang.info
#    email: 'qiwihui@qiwihui.com'
#
#sitemap:
#    file: "/sitemap.xml"
#    exclude:
#        - "/404.html"
#        - "/feed.xml"
#        - "/feed/index.xml"
#    include_posts:
#        - "/index.html"
#    change_frequency_name: "change_frequency"
#    priority_name: "priority"
#
#gems:
#  - jekyll-redirect-from


# Site settings
title: qiwihui
email: qiwihui@qiwihui.com
description: > # this means to ignore newlines until "baseurl:"
  Let's rock python!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qiwihui.com" # the base hostname & protocol for your site
twitter_username: upchaos
github_username:  qiwihui

# Build settings
markdown: kramdown