title:            "daozhang.info"
description:      "Qiwihui's page"
url:              "http://blog.daozhang,info"
signoff:          "Chris.Q"
disqus_shortname: "chris.q"
facebook_appid:   ""
google_analytics: ""

links:
  - name:         Blog
    url:          /
  - name:         RSS
    url:          /atom.xml
  - name:         About
    url:          /about.html
pygments:         true
permalink:        /:title
markdown:         rdiscount
paginate: 8
