## Dependencies
#markdown: redcarpet
highlighter: rouge
#redcarpet:
#    extensions:
#        - footnotes
#
## Permalinks
permalink: pretty
#
## Allows custom plugins to run
#safe: false
#
## Setup
tagline: "qiwihui's thoughts and writings."
sidebar_description: "code, life and thinking"
#
#meta_description: "All things web, mathematics and programming."
#keywords: [Programming, Python, Golang, Mathematics]
encoding: utf-8
#
exclude:
    - Gemfile
    - Gemfile.lock
    - _config.yml

author:
    name: 'qiwihui'
    url: https://qiwihui.com
    email: 'qiwihui@qiwihui.com'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

#gems:
#  - jekyll-redirect-from


# Site settings
title: qiwihui
email: qiwihui@qiwihui.com
description: > # this means to ignore newlines until "baseurl:"
  Let's rock python!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.qiwihui.com" # the base hostname & protocol for your site
twitter_username: upchaos
github_username:  qiwihui

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:qiwihui/qiwihui.github.io.git
  branch: gh-pages