auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: daozhang.info
description: Qiwihui's page
url: http://blog.daozhang.info
feed: /atom.xml
author_info: <a href="http://blog.daozhang.info">Daozhang</a>
