title:            "blog.daozhang.info"
description:      "Qiwihui's page"
url:              "http://blog.daozhang.info"
signoff:          "Chris.Q"
disqus_shortname: "blogdaozhanginfo"
facebook_appid:   ""
google_analytics: ""

links:
  - name:         blog
    url:          /
  - name:         rss
    url:          /feed.xml
  - name:         about
    url:          /about.html
highlighter:      pygments
permalink:        /:title
markdown:         rdiscount
paginate:         8
